### ISSUE TITLE
Added images aren't synchronised with the first image

### ISSUE THREAD

**Issue by schuettelglas** [fiji/3D_Viewer#16]
Operating system: Mac 10.11.1 
Java 1.8.0_65 (64-bit) 
ImageJ 1.50e

I opened two animated gif images in Fiji and used 3D Viewer to display the first image. Then I added the second image to the first image using "add". The second image was added, but when I tried to move the combined image, the second and first image didn't not move together.

**Comment by acardona** [comment]
@schuettelglas , either click and drag outside of the objects, or first lock the transform of the objects. It would be ideal if the transform was locked by default, but the creator of the 3D Viewer primarily used it to register confocal stacks to each other by hand, so that aspect somehow remained forever. Ideally, whether the newly added objects are locked by default--and therefore rotate together with to the world--could be an option stored in ImageJ's preferences file.

**Comment by schuettelglas** [comment]
@acardona  Thanks, that works well!
